# Generated by Django 4.2.20 on 2025-05-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=150)),
                ('complement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField()),
                ('payment_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateField()),
                ('register_date', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.address')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.client')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.state')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRelic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.adoption')),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.relic')),
            ],
        ),
        migrations.AddField(
            model_name='adoption',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions_received', to='records.client'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='previous_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoptions_given', to='records.client'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.city'),
        ),
    ]
