# Generated by Django 4.2.20 on 2025-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relic',
            name='adoption_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relic',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='relic',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='relic',
            name='obtained_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
