# Generated by Django 4.2.20 on 2025-08-28 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0003_client_created_by_relic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrelic',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adoption_relics', to=settings.AUTH_USER_MODEL),
        ),
    ]
