# Generated by Django 5.2.5 on 2025-09-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20250904_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='relic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adoptions', to='records.relic'),
        ),
    ]
