# Generated by Django 4.2.20 on 2025-09-04 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import records.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0007_alter_adoptionrelic_options_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Foto de perfil do cliente (opcional)', null=True, upload_to=records.models.client_photo_upload_path),
        ),
        migrations.CreateModel(
            name='RelicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Imagem da relíquia', upload_to=records.models.relic_image_upload_path)),
                ('is_main', models.BooleanField(default=False, help_text='Marcar como imagem principal')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relic_images', to=settings.AUTH_USER_MODEL)),
                ('relic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.relic')),
            ],
            options={
                'verbose_name': 'Imagem da Relíquia',
                'verbose_name_plural': 'Imagens das Relíquias',
                'ordering': ['-is_main', 'upload_date'],
            },
        ),
    ]
